package com.eventi;

public enum FieldsEventi {
	CAMPO_NOME_EVENTO,
	CAMPO_INDIRIZZO,
	CAMPO_COMUNE,
	CAMPO_PROVINCIA,
	CAMPO_CATEGORIA,
	CAMPO_LUOGO,
	CAMPO_PERIODO,
	CAMPO_ORGANIZZATORE,
	CAMPO_DESCRIZIONE,
	CAMPO_IMAGE_LOGO,
	CAMPO_IMAGE_COPERTINA,
	CAMPO_IMAGE_GALLERIA_1,
	CAMPO_IMAGE_GALLERIA_2,
	CAMPO_IMAGE_GALLERIA_3,
	CAMPO_IMAGE_GALLERIA_4,
	CAMPO_IMAGE_GALLERIA_5,
	CAMPO_INFOMOBILITA,
	CAMPO_FONTE
}
